spring:
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-jwt.yml
      - classpath:application-email.yml
      - classpath:application-s3.yml
      - classpath:application-oauth.yml
      - classpath:application-ssl.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error