spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  data:
    mongodb:
      uri:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    database: mysql
  redis:
    host:
    port:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket:
    region:
      static:
    stack:
      auto: false
jwt:
  secret:
  token:
    access-expiration-time:
    refresh-expiration-time:
logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
frontend:
  host:
  port:
